const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data');
const ELEMENTS_FILE = path.join(DATA_DIR, 'elements.json');

if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

const elements = [
  { id:1, name_es:'Manzanilla', name_en:'Chamomile', scientific_name:'Matricaria chamomilla', category:'flower', element:'Agua', planet:'Sol & Luna', chakra:null, body_benefits:'Antiinflamatoria, antiespasmódica, sedante suave. Ideal para cólicos, gastritis, indigestión, insomnio y ansiedad. Calma irritaciones de piel, eczema y quemaduras leves.', spiritual_benefits:'Hierba de la PAZ y PROSPERIDAD. Atrae abundancia económica. Calma la energía agitada del hogar, deshace discusiones. Promueve sueños pacíficos.', uses:'Té: 1 cucharada flores secas, 5-10 min\nBaño de limpia: flores en agua tibia para paz y abundancia\nSteam facial: para piel sensible\nCompresa fría: para ojos hinchados', precautions:'Puede causar reacción alérgica en personas sensibles a la familia Asteraceae.' },
  { id:2, name_es:'Caléndula', name_en:'Calendula', scientific_name:'Calendula officinalis', category:'flower', element:'Fuego', planet:'Sol', chakra:null, body_benefits:'La GRAN SANADORA de la piel. Cicatrizante, antifúngica, antiinflamatoria. Para heridas, quemaduras leves, dermatitis, rozaduras.', spiritual_benefits:'PROTECCIÓN y VISIÓN. Induce sueños proféticos bajo la cama. Guardiana solar en umbrales. Atrae justicia.', uses:'Aceite infusionado: flores en aceite 4-6 semanas\nTé suave: inflamación interna\nBaño de limpia: protección y vitalidad\nCataplasma: sobre heridas', precautions:'No ingerir durante el embarazo.' },
  { id:3, name_es:'Menta', name_en:'Mint', scientific_name:'Mentha piperita', category:'herb', element:'Aire', planet:'Mercurio', chakra:null, body_benefits:'DESPERTAR INSTANTÁNEO. Digestiva, descongestionante, analgésica para dolor de cabeza.', spiritual_benefits:'CAMINOS ABIERTOS y PROSPERIDAD. Atrae dinero y clientes. Limpia bloqueos.', uses:'Té: hojas frescas o secas\nSteam: congestión y claridad mental\nBaño de limpia: abrir caminos\nAceite en sienes: dolor de cabeza', precautions:'Evitar aceite esencial en niños <3 años. Moderar durante lactancia.' },
  { id:4, name_es:'Gordolobo', name_en:'Mullein', scientific_name:'Verbascum thapsus', category:'herb', element:'Fuego', planet:'Saturno', chakra:null, body_benefits:'GUARDIÁN DE LOS PULMONES. Expectorante, demulcente. Para tos, bronquitis, asma.', spiritual_benefits:'CORAJE y PROTECCIÓN ANCESTRAL. Aleja pesadillas, desterra espíritus negativos.', uses:'Té: SIEMPRE filtrar con tela fina\nSteam: abrir pulmones\nAceite de flores: dolor de oídos\nSahumerio: protección', precautions:'SIEMPRE colar con filtro de tela.' },
  { id:5, name_es:'Salvia', name_en:'Sage', scientific_name:'Salvia officinalis / S. apiana', category:'herb', element:'Aire', planet:'Júpiter', chakra:null, body_benefits:'MEDICINA FEMENINA. Regula hormonas, alivia menopausia. Antiséptica para garganta. Mejora memoria.', spiritual_benefits:'MAESTRA DE LA LIMPIEZA ENERGÉTICA. Purifica espacios, personas y objetos.', uses:'Sahumerio/Smudge: humo recorre espacio\nTé: garganta y memoria\nGárgaras: infecciones orales\nBaño de limpia: cortar ataduras', precautions:'No en exceso durante embarazo/lactancia. Salvia blanca es sagrada — usar con respeto.' },
  { id:6, name_es:'Romero', name_en:'Rosemary', scientific_name:'Rosmarinus officinalis', category:'herb', element:'Fuego', planet:'Sol', chakra:null, body_benefits:'CIRCULACIÓN Y MEMORIA. Estimula flujo sanguíneo, fortalece cabello. Antioxidante.', spiritual_benefits:'PROTECCIÓN, PURIFICACIÓN y RECUERDO. Protege el hogar. Fortalece fidelidad.', uses:'Té: circulación y memoria\nAgua de romero: enjuague capilar\nBaño de limpia: protección\nSahumerio: purificación', precautions:'Evitar dosis altas en embarazo. No ingerir aceite esencial.' },
  { id:7, name_es:'Flor de Jamaica', name_en:'Hibiscus', scientific_name:'Hibiscus sabdariffa', category:'flower', element:'Agua', planet:'Venus', chakra:null, body_benefits:'CORAZÓN SANO. Reduce presión arterial, baja colesterol, rica en vitamina C y antioxidantes.', spiritual_benefits:'AMOR PROPIO, PASIÓN y DIVINIDAD FEMENINA. Abre corazón. Sensualidad sagrada.', uses:'Té/Agua fresca: salud cardiovascular\nBaño de limpia: amor propio\nSteam facial: piel radiante\nPoción: jamaica con miel y canela', precautions:'Puede bajar presión en exceso en personas hipotensas.' },
  { id:8, name_es:'Ruda', name_en:'Rue', scientific_name:'Ruta graveolens', category:'herb', element:'Fuego', planet:'Marte & Sol', chakra:null, body_benefits:'Antiespasmódica, emenagoga, repelente de insectos, antimicrobiana externa.', spiritual_benefits:'REINA DE LA PROTECCIÓN. Rompe mal de ojo, envidia, brujería. Guardiana incansable.', uses:'Ramo detrás de puerta: protección\nBaño de limpia: romper envidia\nAgua de ruda: limpiar negocios\nPlanta viva: guardiana en entrada', precautions:'TÓXICA internamente. NUNCA en embarazo — ABORTIVA. Solo uso externo. Fotosensibilidad.' },
  { id:9, name_es:'Artemisa', name_en:'Mugwort', scientific_name:'Artemisia vulgaris', category:'herb', element:'Tierra', planet:'Luna & Venus', chakra:null, body_benefits:'MEDICINA LUNAR. Regula ciclo menstrual, alivia cólicos, digestiva, antiparasitaria.', spiritual_benefits:'PLANTA DE LOS SUEÑOS. Sueños lúcidos y proféticos. Activa tercer ojo.', uses:'Sachet bajo almohada: sueños lúcidos\nTé antes de dormir: visiones\nSahumerio: portales intuitivos\nBaño de limpia: despertar intuición', precautions:'No en embarazo. No en exceso prolongado.' },
  { id:10, name_es:'Lavanda', name_en:'Lavender', scientific_name:'Lavandula angustifolia', category:'flower', element:'Aire', planet:'Mercurio', chakra:null, body_benefits:'PAZ LÍQUIDA. Ansiolítica, reduce cortisol, alivia insomnio y dolor de cabeza tensional.', spiritual_benefits:'ARMONÍA y AMOR PACÍFICO. Calma discusiones, armoniza el aura.', uses:'Té: ansiedad e insomnio\nAceite esencial: difusor, almohada\nBaño de limpia: paz emocional\nSachets: cajones y almohada', precautions:'Muy segura. Precaución prolongada en niños prepúberes.' },
  { id:11, name_es:'Rosas', name_en:'Roses', scientific_name:'Rosa spp.', category:'flower', element:'Agua', planet:'Venus', chakra:null, body_benefits:'BELLEZA DESDE ADENTRO. Tonifica piel, escaramujo rico en vitamina C. Calma ansiedad.', spiritual_benefits:'AMOR EN SU FORMA MÁS ELEVADA. Vibra en la frecuencia más alta del amor. Ofrenda universal.', uses:'Agua de rosas: tónico y rituales\nTé de pétalos: calmar corazón\nBaño de limpia: amor propio\nOfrenda: pétalos en altar', precautions:'Usar SOLO rosas orgánicas para consumo.' },
  { id:12, name_es:'Árnica', name_en:'Arnica', scientific_name:'Arnica montana', category:'herb', element:'Fuego', planet:'Sol', chakra:null, body_benefits:'SANADOR DE GOLPES. Antiinflamatorio para moretones, hematomas, dolor muscular.', spiritual_benefits:'RESILIENCIA Y RECUPERACIÓN. Sana los golpes de la vida.', uses:'Aceite/Crema tópica: moretones y dolor\nCompresa tibia: inflamación\nBaño de pies: cansancio extremo', precautions:'SOLO USO EXTERNO. Tóxica si se ingiere. NUNCA sobre heridas abiertas.' },
  { id:13, name_es:'Toronjil', name_en:'Lemon Balm', scientific_name:'Melissa officinalis', category:'herb', element:'Agua', planet:'Luna', chakra:null, body_benefits:'CALMA PROFUNDA. Ansiolítica, antiviral (herpes), digestiva.', spiritual_benefits:'CORAZÓN SANADO y DULZURA. Atrae amistades verdaderas. Alivia duelo.', uses:'Té: calma y antiviral\nCompresa: sobre herpes labial\nBaño de limpia: sanar corazón\nSachets: atraer amor genuino', precautions:'Puede interferir con medicamentos tiroideos.' },
  { id:14, name_es:'Eucalipto', name_en:'Eucalyptus', scientific_name:'Eucalyptus globulus', category:'herb', element:'Agua', planet:'Luna', chakra:null, body_benefits:'RESPIRACIÓN LIBRE. Descongestionante poderoso, antiséptico, febrífugo.', spiritual_benefits:'SANACIÓN y RENOVACIÓN ENERGÉTICA. Limpia energía de enfermedad.', uses:'Steam: inhalar con toalla\nBaño de limpia: limpiar enfermedad\nSahumerio: purificar espacios\nEn regadera: ramo colgado', precautions:'No aceite esencial en cara de niños <3 años. No ingerir.' },
  { id:15, name_es:'Jazmín', name_en:'Jasmine', scientific_name:'Jasminum officinale', category:'flower', element:'Agua', planet:'Luna & Venus', chakra:null, body_benefits:'SENSUALIDAD Y CALMA. Antidepresivo aromático, mejora sueño.', spiritual_benefits:'AMOR DIVINO y LUNA SAGRADA. Atrae amor verdadero y almas afines.', uses:'Aceite esencial: amor y autoestima\nTé suave: calmar nervios\nBaño de limpia: atraer amor\nOfrenda a la luna: flores bajo luna llena', precautions:'Desconfiar de aceites baratos (sintéticos). No ingerir aceite esencial.' },
  { id:16, name_es:'Canela', name_en:'Cinnamon', scientific_name:'Cinnamomum verum', category:'spice', element:'Fuego', planet:'Sol & Marte', chakra:null, body_benefits:'FUEGO SANADOR. Regula azúcar, antimicrobiana, estimula circulación, termogénica.', spiritual_benefits:'ABUNDANCIA INSTANTÁNEA y ACELERACIÓN. Atrae dinero rápido. Acelera todo trabajo espiritual.', uses:'Té: circulación y calor\nRitual del 1°: soplar canela en puerta\nBaño de limpia: abundancia\nSahumerio: activar energía', precautions:'Canela CASSIA en exceso daña hígado. Preferir CEILÁN para uso frecuente.' },
  { id:17, name_es:'Clavos de Olor', name_en:'Cloves', scientific_name:'Syzygium aromaticum', category:'spice', element:'Fuego', planet:'Júpiter', chakra:null, body_benefits:'ANALGESIA NATURAL. Eugenol para dolor de muelas. Antiséptico, antiparasitario.', spiritual_benefits:'SILENCIADOR DE CHISMES. Cierra bocas. Protege contra envidia. Imán de prosperidad.', uses:'Té: 3-4 clavos para digestión\nDolor de muelas: clavo directo\nBaño de limpia: cortar chismes\nEn cartera: 3 clavos para dinero', precautions:'Aceite esencial muy concentrado — siempre diluir.' },
  { id:18, name_es:'Semillas de Saúco', name_en:'Elderberry', scientific_name:'Sambucus nigra', category:'spice', element:'Agua', planet:'Venus', chakra:null, body_benefits:'INMUNIDAD PODEROSA. Antiviral, reduce gripes. Rico en vitamina C.', spiritual_benefits:'ÁRBOL ANCESTRAL. Conecta con ancestros. Energía de abuela sabia protectora.', uses:'Jarabe: bayas cocidas con miel\nTé: bayas cocidas para inmunidad\nBaño de limpia: protección ancestral', precautions:'Bayas CRUDAS son TÓXICAS. SIEMPRE cocinar antes de consumir.' },
  { id:19, name_es:'Limón', name_en:'Lemon', scientific_name:'Citrus limon', category:'spice', element:'Agua', planet:'Luna', chakra:null, body_benefits:'DESINTOXICACIÓN Y VITALIDAD. Alcaliniza, apoya hígado, vitamina C, antibacteriano.', spiritual_benefits:'CORTE Y LIMPIEZA RADICAL. Absorbe energía negativa. Detecta envidias. Corta lazos.', uses:'Agua con limón: desintoxicación\nBaño de limpia: cortar negatividad\nEn esquinas: absorber mala energía\nLectura: partir limón post-limpia', precautions:'Erosiona esmalte dental. Jugo + sol = quemaduras (fitofotodermatitis).' },
  { id:20, name_es:'Avena', name_en:'Oats', scientific_name:'Avena sativa', category:'spice', element:'Tierra', planet:'Venus', chakra:null, body_benefits:'NUTRICIÓN Y RESTAURACIÓN. Emoliente para piel, alimenta nervios, reduce colesterol.', spiritual_benefits:'ABUNDANCIA TERRENAL y ESTABILIDAD. Prosperidad constante. Grounding.', uses:'Baño de avena: piel y protección\nTé de paja: nervios exhaustos\nSachets: prosperidad\nOfrenda a la tierra: esparcir en jardín', precautions:'Celíacos: verificar avena certificada sin gluten.' },
  { id:21, name_es:'Arroz', name_en:'Rice', scientific_name:'Oryza sativa', category:'spice', element:'Tierra', planet:'Sol', chakra:null, body_benefits:'Agua de arroz: tonifica piel, hidrata cabello, calma estómago.', spiritual_benefits:'FERTILIDAD, ABUNDANCIA y BENDICIÓN. Tarro que nunca se vacíe = abundancia infinita.', uses:'Agua de arroz: piel y cabello\nBaño de limpia: abundancia\nEn esquinas: protección\nTarro con moneda: ritual abundancia', precautions:'Sin contraindicaciones en uso externo.' },
  { id:22, name_es:'Sal', name_en:'Salt', scientific_name:'NaCl', category:'mineral', element:'Tierra', planet:'Tierra', chakra:null, body_benefits:'PURIFICACIÓN MINERAL. Antiséptica, exfoliante, descongestiva nasal, relajante muscular.', spiritual_benefits:'PILAR de protección y limpieza. Absorbe toda energía negativa. Crea barreras. Universal.', uses:'Baño de sal: limpieza profunda\nLíneas en puertas: barrera\nEn rincones: absorber negatividad\nScrub: piel renovada', precautions:'No en heridas abiertas. Enjuagar e hidratar después.' },
  { id:23, name_es:'Magnesio', name_en:'Magnesium', scientific_name:'MgSO4', category:'mineral', element:'Tierra', planet:'Saturno', chakra:null, body_benefits:'RESTAURACIÓN PROFUNDA. Relajante muscular, reduce estrés, mejora sueño.', spiritual_benefits:'ANCLAJE Y SOLTAR. Grounding profundo. Ayuda a soltar patrones. Recalibra cuerpo energético.', uses:'Baño: 2 tazas sales Epsom, 20 min\nFoot soak: grounding rápido\nCon aceites: efecto dual\nPost-ritual: restaurar cuerpo', precautions:'Precaución con problemas renales. No ingerir sin supervisión.' },
  { id:24, name_es:'Cristales de Menta', name_en:'Mint Crystals', scientific_name:'L-Menthol', category:'mineral', element:'Aire', planet:'Mercurio', chakra:null, body_benefits:'POTENCIA CONCENTRADA. Analgésico tópico, descongestionante poderoso.', spiritual_benefits:'CLARIDAD MENTAL INSTANTÁNEA. Abren tercer ojo, despejan confusión.', uses:'Steam: 2-3 cristales máximo\nBaño de pies: refrescar\nEn aceite: masaje dolor\nMeditación: tercer ojo', precautions:'EXTREMADAMENTE CONCENTRADO. Lejos de ojos. NO niños <6 años. Quema piel sin diluir.' },
  { id:25, name_es:'Frankincense', name_en:'Frankincense', scientific_name:'Boswellia sacra', category:'mineral', element:'Fuego', planet:'Sol', chakra:null, body_benefits:'ANTIINFLAMACIÓN SAGRADA. Para artritis, dolor crónico. Inmunomodulador.', spiritual_benefits:'CONEXIÓN CON LO DIVINO. Resina sagrada de TODAS las tradiciones. Eleva vibración al máximo.', uses:'Sahumerio: resina sobre carbón\nMeditación: conexión divina\nOración: acompaña peticiones\nAceite diluido: dolor articular', precautions:'Humo excesivo sin ventilación irrita vías respiratorias.' },
  { id:26, name_es:'Ojo de Tigre', name_en:'Tiger Eye', scientific_name:'Cuarzo microcristalino', category:'mineral', element:'Fuego', planet:'Sol', chakra:'Plexo Solar', body_benefits:'Fortalece sistema digestivo, estabiliza energía vital, grounding táctil.', spiritual_benefits:'PROTECCIÓN GUERRERA y EMPODERAMIENTO. Coraje, confianza, poder personal. Atrae prosperidad por ACCIÓN.', uses:'Llevar encima: protección diaria\nEn negocio: atraer clientes\nMeditación: sobre plexo solar\nEntrevistas: en bolsillo', precautions:'Limpiar con sahumerio o luna. Cargar al sol. No agua salada prolongada.' },
];

// Always seed if file is empty or missing
let existing = [];
try { existing = JSON.parse(fs.readFileSync(ELEMENTS_FILE, 'utf8')); } catch(e) {}

if (existing.length === 0) {
  elements.forEach(el => { el.created_at = new Date().toISOString(); el.updated_at = el.created_at; el.image_url = null; });
  fs.writeFileSync(ELEMENTS_FILE, JSON.stringify(elements, null, 2));
  console.log(`✦ Seeded ${elements.length} elements into the grimoire.`);
} else {
  console.log(`✦ Grimoire already has ${existing.length} elements. Skipping seed.`);
}
